name: Deploy to Github Packages

on:
  push:
    branches:
      - master

jobs:
  install:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install correct npm version 8
        run: npm -g install npm@8.3.1
      - name: npm install
        run: npm install
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: src/

  publish-package-to-github:
    runs-on: macos-latest
    needs: install
    name: publish to github packages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download built artifact
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: src
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install correct npm version 8
        run: npm -g install npm@8
      - name: Publish to Github Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-package-to-npm:
    runs-on: macos-latest
    needs: install
    name: publish to npm
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download built artifact
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: src
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install correct npm version 8
        run: npm -g install npm@8
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
