name: Deploy to Github Packages

on:
  push:
    branches:
      - master
      - ado-81920-typescript

jobs:
  install:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: npm install
        run: npm install
      - name: Upload built artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: src/

  publish-package-to-github:
    runs-on: macos-latest
    needs: install
    name: publish to github packages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download built artifact
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: src
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://npm.pkg.github.com'
      - name: Publish to Github Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-package-to-npm:
    runs-on: macos-latest
    needs: install
    name: publish to npm
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download built artifact
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: src
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
