name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node-version: ['18', '20']
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
      - run: pnpm install
      - run: pnpm tsc
      - run: pnpm format:check
        if: success() || failure()
      - run: pnpm lint
        if: success() || failure()
      - run: pnpm circular:check
        if: success() || failure()
      - run: pnpm test
        if: success() || failure()
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - uses: github/codeql-action/init@v2
        with:
          languages: javascript-typescript
      - uses: github/codeql-action/analyze@v2
